[package]
name = "pg_proxy"
version = "0.1.0"
authors = ["Ian Purton"]
edition = "2018"

[dependencies]
tokio = { version = "1.10.1", features = ["full"] }
futures = "0.3"
#tokio-util = { version = "0.6.3", features = ["full"] }
#tokio-stream = { version = "0.1" }